[target.x86_64-unknown-linux-gnu]
linker = "gcc"
rustflags = ["-Zshare-generics=y", "-C", "link-arg=-fuse-ld=mold"]

# [unstable]
# codegen-backend = true

# [profile.dev]
# strip = "symbols"
# codegen-backend = "cranelift"
 
# [profile.release]
# lto = "thin"

[build]
target-dir = "/mnt/hd/rust-target"
