# brightness with binde
binde = , XF86MonBrightnessUp, exec, $SCRIPTS/brightness.sh +
binde = , XF86MonBrightnessDown, exec, $SCRIPTS/brightness.sh -
binde = $HYPER, e, exec, $SCRIPTS/brightness.sh +
binde = $HYPER, w, exec, $SCRIPTS/brightness.sh -
