# brightness with binde
binde = , XF86MonBrightnessUp, exec, ~/.config/hypr/brightness.sh +
binde = , XF86MonBrightnessDown, exec, ~/.config/hypr/brightness.sh -
binde = $HYPER, e, exec, ~/.config/hypr/brightness.sh +
binde = $HYPER, w, exec, ~/.config/hypr/brightness.sh -
