# brightness without binde
bind = , XF86MonBrightnessUp, exec, ~/.config/hypr/brightness.sh +
bind = , XF86MonBrightnessDown, exec, ~/.config/hypr/brightness.sh -
bind = $HYPER, e, exec, ~/.config/hypr/brightness.sh +
bind = $HYPER, w, exec, ~/.config/hypr/brightness.sh -
